services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /srv
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/app:/srv/app:rw
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - DEFAULT_PROVIDER=${DEFAULT_PROVIDER:-auto}
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
